name = "NFFTTools"
uuid = "7424e34d-94f7-41d6-98a0-85abaf1b6c91"
author = ["Tobias Knopp <tobias@knoppweb.de>"]
version = "0.2.3"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c" 
AbstractNFFTs = "7f219486-4aa7-41d6-80a7-e08ef20ceed7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
julia = "1.6"
AbstractFFTs = "1.0"
AbstractNFFTs = "0.6, 0.7, 0.8"
FFTW = "1"
