name = "AbstractNFFTs"
uuid = "7f219486-4aa7-41d6-80a7-e08ef20ceed7"
author = ["Tobias Knopp <tobias@knoppweb.de>"]
version = "0.9.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
ScopedValues = "7e506255-f358-4e82-b7e4-beb19740aa63"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"

[extensions]
AbstractNFFTsChainRulesCoreExt = "ChainRulesCore"

[compat]
julia = "1.6"
ChainRulesCore = "1"
Requires = "1"
ScopedValues = "1"
