name = "CuNFFT"
uuid = "a9291f20-7f4c-4d50-b30d-4e07b13252e1"
author = ["Tobias Knopp <tobias@knoppweb.de>"]
version = "0.1"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c" 
AbstractNFFTs = "7f219486-4aa7-41d6-80a7-e08ef20ceed7"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NFFT = "efe261a4-0d2b-5849-be55-fc731d526b0d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1.6"
AbstractFFTs = "1.0"
AbstractNFFTs = "0.2.2"
CUDA = "1.3.3, 2.3, 3.1"
NFFT = "0.7"
Reexport = "1.0"
